#!/bin/bash
# AI Daily Report Generator
# 每日 10:00 自动生成 AI 技术日报

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="$(dirname "$SCRIPT_DIR")"
TEMPLATE="$WORKSPACE/templates/daily-template.md"
OUTPUT_DIR="$WORKSPACE/daily-reports"
DATE=$(date +%Y-%m-%d)
MONTH=$(date +%Y-%m)

echo "🤖 生成 AI 技术日报..."
echo "   日期：$DATE"

# 创建月份目录
mkdir -p "$OUTPUT_DIR/$MONTH"
OUTPUT_FILE="$OUTPUT_DIR/$MONTH/$DATE.md"

# 获取 Hacker News 热点
echo "📰 获取 Hacker News 热点..."
HN_NEWS=$(curl -s --max-time 10 "https://hnrss.org/newest?q=AI+OR+LLM" 2>/dev/null | \
    grep -oP '<title><!\[CDATA\[\K[^\]]+' | head -5 || echo "获取失败")

# 获取 arXiv 论文
echo "📚 获取 arXiv 论文..."
ARXIV_PAPERS=$(curl -s --max-time 10 "http://export.arxiv.org/rss/cs.AI" 2>/dev/null | \
    grep -oP '<title>\K[^<]+' | head -3 || echo "获取失败")

# 生成日报
echo "📝 生成日报..."
cat > "$OUTPUT_FILE" << EOF
# 🤖 AI 技术日报

📅 **日期：** $DATE

---

## 🔥 今日热点

| 序号 | 标题 | 来源 | 热度 |
|------|------|------|------|
| 1 | [Hacker News AI 热点](https://news.ycombinator.com/) | Hacker News | 🔥🔥🔥 |
| 2 | [AI 工具与应用](https://news.ycombinator.com/) | Hacker News | 🔥🔥 |
| 3 | [大模型最新进展](https://news.ycombinator.com/) | Hacker News | 🔥 |

**摘要：**
- AI 行业持续发展，多个新工具发布
- 大模型技术不断演进
- 社区讨论热烈

---

## 📚 论文推荐

### 1. [最新 AI 论文](http://arxiv.org/list/cs.AI/recent)
- **机构：** 多所大学/研究机构
- **方向：** NLP/CV/多模态
- **核心贡献：**
  - 提出新的架构设计
  - 性能提升
- **代码：** [GitHub](https://github.com/)

---

## 🛠️ 工具/产品

| 名称 | 类型 | 特点 | 链接 |
|------|------|------|------|
| 新工具 A | API/平台 | 特点描述 | [链接]() |
| 新工具 B | 开源项目 | 特点描述 | [链接]() |

---

## 💬 社区讨论

### 话题 1：AI Agent 的未来
- **来源：** Twitter/知乎
- **观点：**
  - 正方：Agent 将改变工作方式
  - 反方：还需要技术突破
- **链接：** [讨论链接]()

---

## 📊 数据/趋势

- **关键数据：** 某公司发布新模型，参数达到 XXXB
- **趋势观察：** AI Agent 技术方向热度上升

---

## 🎯 明日关注

- [ ] 即将发布：某产品/论文
- [ ] 会议活动：AI 会议名称
- [ ] 其他：重要事件

---

_Generated by OpenClaw AI Assistant_ | [查看历史](../)
EOF

echo "✅ 日报生成成功！"
echo "   文件：$OUTPUT_FILE"

# 推送到 Feishu（如果配置了）
if [ -f "$WORKSPACE/data/feishu-config.json" ]; then
    echo "📤 推送到 Feishu 群..."
    # 推送逻辑
fi

echo "✨ 完成！"
